db:
  image: eoger/postgis:latest
  env_file: conf.env

routing:
  build: routing
  ports:
   - "8888:8888"

api:
  build: api
  env_file: conf.env
  environment:
    PYTHONDONTWRITEBYTECODE: true
  links:
   - db
  volumes:
   - ./api/:/usr/src/app

worker:
  build: worker
  env_file: conf.env
  links:
   - db

proxy:
    build: proxy
    env_file: conf.env
    links:
        - api:flask
    ports:
        - "8080:80"
