db:
  image: jamesbrink/postgresql:latest
  env_file: conf.env

api:
  build: api
  env_file: conf.env
  environment:
    PYTHONDONTWRITEBYTECODE: true
  links:
   - db
  volumes:
   - ./api/:/usr/src/app

worker:
  build: worker
  env_file: conf.env
  links:
   - db

routing:
  build: routing

proxy:
  build: proxy
  env_file: conf.env
  links:
   - api:flask
   - routing:brouter
  ports:
   - "80:80"
   
