db:
  image: jamesbrink/postgresql:latest
  env_file: conf.env

api:
  build: api
  env_file: conf.env
  links:
   - db
   - routing:brouter
  volumes:
   - ./api/app:/home/docker/code/app
  ports:
   - "80:80"

worker:
  build: worker
  env_file: conf.env
  links:
   - db

routing:
  build: routing
<<<<<<< HEAD
=======

proxy:
  build: proxy
  env_file: conf.env
  links:
   - api:flask
   - routing:brouter
  ports:
   - "8080:80"
   
>>>>>>> a8bed53145dec21ec4261a732720e7c8999f036e
