dbdata:
  image: eoger/postgis:latest
  command: /bin/true

db:
  image: eoger/postgis:latest
  volumes_from:
   - dbdata
  env_file: conf.env

api:
  build: api
  env_file: conf.env
  environment:
    PYTHONDONTWRITEBYTECODE: true
  links:
   - db
  volumes:
   - ./api/:/usr/src/app
  ports:
   - "5000:5000"

worker:
  build: worker
  env_file: conf.env
  links:
   - db
