dbdata:
  image: mdillon/postgis
  command: /bin/true

db:
  image: mdillon/postgis
  volumes_from:
   - dbdata
  environment:
    POSTGRES_DB: velov-companion

api:
  build: .
  environment:
    PYTHONDONTWRITEBYTECODE: true
  links:
   - db
  volumes:
   - .:/usr/src/app
  ports:
   - "5000:5000"
