db:
  image: eoger/postgis:latest
  env_file: conf.env

routing:
  build: routing
  ports:
   - "8888:8888"

api:
  build: api
  env_file: conf.env
  environment:
    PYTHONDONTWRITEBYTECODE: true
  links:
   - db
  volumes:
   - ./api/:/usr/src/app
  ports:
   - "5000:5000"

worker:
  build: worker
  env_file: conf.env
  links:
   - db
